version: "3.9"
services:
  web:
    image: johannesegger/musiscore:0.1
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - /opt/musiscore/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=musiscore
      - POSTGRES_PASSWORD_FILE=/run/secret/db_password
    secrets:
      - db_password
  print:
    image: ydkn/cups
    volumes:
      - /opt/musiscore/print:/etc/cups
secrets:
  db_password:
    file: ./db_password.txt
