services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: ./src/Dockerfile
  #   ports:
  #     - 8080:80
  #   environment:
  #     - ConnectionStrings__Db=Host=db;Database=musiscore;User ID=musiscore;Password=test1234;
  #     - Print__Server=print
  #     - Print__Printer=Ricoh-Aficio-3025
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/app/data
      - ./db-schema.sql:/docker-entrypoint-initdb.d/01-db-schema.sql
      - ./db-sample.sql:/docker-entrypoint-initdb.d/02-db-sample.sql
    environment:
      - POSTGRES_USER=musiscore
      - POSTGRES_PASSWORD=test1234
  adminer:
    image: adminer
    ports:
      - 8081:8080
  print:
    build:
      context: ./cups-docker
    ports:
      - 8082:631
    volumes:
      - .\print:/etc/cups
