services:
  web:
    image: ghcr.io/wk-laufen/musiscore:c869291596e5ed8c6cc6027ec9be830f2357821c
    restart: unless-stopped
    ports:
      - 80:8080
    environment:
      - Db_ConnectionString_File=/run/secrets/db_connection_string
      - Print__Server=print
      - Print__Printer=Ricoh-Aficio-3025
      - APIKeys__abcdef__0=Notenarchivar
    secrets:
      - db_connection_string
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - /opt/musiscore/db:/var/lib/postgresql/data
      - ./db-schema.sql:/docker-entrypoint-initdb.d/01-db-schema.sql
    environment:
      - POSTGRES_USER=musiscore
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
  print:
    image: ydkn/cups
    restart: unless-stopped
    ports:
      - 81:631
    volumes:
      - /opt/musiscore/print:/etc/cups
secrets:
  db_password:
    file: ./db_password.txt
  db_connection_string:
    file: ./db_connection_string.txt
