version: "3.9"
services:
  web:
    image: johannesegger/musiscore:0.1
  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - /opt/musiscore/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=musiscore
      - MYSQL_ROOT_PASSWORD_FILE=/run/secret/db_password
    secrets:
      - db_password
  print:
    image: ydkn/cups
    volumes:
      - /opt/musiscore/print:/etc/cups
secrets:
  db_password:
    file: ./db_password.txt
