name: Publish

on:
  push:
  workflow_dispatch: # Allow manual trigger

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Run server tests
        run: dotnet test

      - name: Run client tests
        working-directory: ./src/MusiScore.Client
        run: npm test

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push CUPS container image to registry
        uses: docker/build-push-action@v6
        with:
          context: ./cups-docker
          file: ./cups-docker/Dockerfile
          push: true
          tags: ghcr.io/wk-laufen/musiscore-cups:${{ github.sha }}

      - name: Build and push admin app container image to registry
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./src/Dockerfile
          push: true
          tags: ghcr.io/wk-laufen/musiscore:${{ github.sha }}
